### PR TITLE
BDD tests using Behave

### PR DESCRIPTION
**Pull request by iambibhas**
This includes 

 - Tests for failed and successful registration
 - Tests for failed and successful login

### CODE REVIEW

**Comment by jace** [comment]
@iambibhas can you rebase this on the `userid-to-buid` branch?

**Comment by iambibhas** [comment]
@jace I dont use rebase much. can you explain the intention for the rebase? want to combine this with your PR?

**Comment by jace** [comment]
Yes. That PR touches a lot of files and is going to master unless we find issues with it.

**Comment by iambibhas** [comment]
@jace pulled this PR into #211. Can close this one.

**Pull request merged**
